---
#- hosts: localhost
#  connection: local
#  roles:
#    - known_hosts

- hosts: apic
  vars_prompt:
    - name: "user"
      prompt: "Username"
      private: no
    - name: "password"
      prompt: "Password"
      private: yes
    - name: "tenant_name"
      prompt: "Which Tenant will the new VRF be created?"
      private: no
    - name: "vrf_name"
      prompt: "What is the name of the VRF?"
      private: no
  gather_facts: no
  connection: local
  roles:
    - aci_vrf_add
