---

- hosts: msc
  vars_prompt:
    - name: "user"
      prompt: "Username"
      private: no
    - name: "password"
      prompt: "Password"
      private: yes
  gather_facts: no
  connection: local
  roles:
    - aci_msc_user_add