---
#- hosts: localhost
#  connection: local
#  roles:
#    - known_hosts

- hosts: apic
  vars_prompt:
    - name: "user"
      prompt: "Username"
      private: no
    - name: "password"
      prompt: "Password"
      private: yes
    - name: "new_user"
      prompt: "New Username to add"
      private: no
    - name: "new_password"
      prompt: "New User's Password"
      private: no
    - name: "first_name"
      prompt: "First Name"
      private: no
    - name: "last_name"
      prompt: "Last Name"
      private: no
    - name: "email"
      prompt: "New User's Email Address"
      private: no
    - name: "phone"
      prompt: "New User's Phone Number"
      private: no
  gather_facts: no
  connection: local
  roles:
    - aci_user_add