- name: create vlan
  nxos_config:
    lines: 
      - vlan {{ vlan_id }}
    username: admin
    password: admin
#    transport: cli

- name: Configure VLAN Name
  nxos_config:
    lines:
      - name VLAN_{{ vlan_id }}
    parents: vlan {{ vlan_id }}
    username: admin
    password: admin
#    transport: cli
