- name: update daemon.json file for native cgroupdriver
  shell:
   cmd: |
    cat << EOF >> /etc/docker/daemon.json
    {
       "exec-opts": ["native.cgroupdriver=systemd"]
    }
    EOF

- name: Remove swapfile from /etc/fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '^/[\S]+\s+none\s+swap '
    state: absent

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

