
- name: Add a new Local User
  aci_aaa_user:
    hostname: 10.207.10.100
    username: "{{ user }}"
    password: "{{ password }}"
    aaa_user: "{{ new_user }}"
    aaa_password: "{{ new_password }}"
    expiration: never
    expires: no
    email: "{{ email }}"
    phone: "{{ phone }}"
    first_name: "{{ first_name }}"
    last_name: "{{ last_name }}"
    state: present
    validate_certs: no 
#  delegate_to: localhost
