- name: Add a new ProvidedContract
  aci_epg_to_contract:
    hostname: 10.207.10.100
    username: "{{ user }}"
    password: "{{ password }}"
    tenant: "{{ tenant_name }}"
    ap: "{{ ap_name }}"
    epg: "{{ epg1_name }}"
    contract: permit_any
    contract_type: provider
    state: present
    validate_certs: no 
#  delegate_to: localhost


- name: Add a new Consumed Contract
  aci_epg_to_contract:
    hostname: 10.207.10.100
    username: "{{ user }}"
    password: "{{ password }}"
    tenant: "{{ tenant_name }}"
    ap: "{{ ap_name }}"
    epg: "{{ epg1_name }}"
    contract: permit_any
    contract_type: consumer
    state: present
    validate_certs: no
#  delegate_to: localhost

- name: Add a new ProvidedContract
  aci_epg_to_contract:
    hostname: 10.207.10.100
    username: "{{ user }}"
    password: "{{ password }}"
    tenant: "{{ tenant_name }}"
    ap: "{{ ap_name }}"
    epg: "{{ epg2_name }}"
    contract: permit_any
    contract_type: provider
    state: present
    validate_certs: no 
#  delegate_to: localhost


- name: Add a new Consumed Contract
  aci_epg_to_contract:
    hostname: 10.207.10.100
    username: "{{ user }}"
    password: "{{ password }}"
    tenant: "{{ tenant_name }}"
    ap: "{{ ap_name }}"
    epg: "{{ epg2_name }}"
    contract: permit_any
    contract_type: consumer
    state: present
    validate_certs: no
#  delegate_to: localhost

- name: Add a new ProvidedContract
  aci_epg_to_contract:
    hostname: 10.207.10.100
    username: "{{ user }}"
    password: "{{ password }}"
    tenant: "{{ tenant_name }}"
    ap: "{{ ap_name }}"
    epg: "{{ epg3_name }}"
    contract: permit_any
    contract_type: provider
    state: present
    validate_certs: no 
#  delegate_to: localhost


- name: Add a new Consumed Contract
  aci_epg_to_contract:
    hostname: 10.207.10.100
    username: "{{ user }}"
    password: "{{ password }}"
    tenant: "{{ tenant_name }}"
    ap: "{{ ap_name }}"
    epg: "{{ epg3_name }}"
    contract: permit_any
    contract_type: consumer
    state: present
    validate_certs: no
#  delegate_to: localhost