---
#- hosts: localhost
#  connection: local
#  roles:
#    - known_hosts

- hosts: apic
  vars_prompt:
    - name: "user"
      prompt: "Username"
      private: no
    - name: "password"
      prompt: "Password"
      private: yes
    - name: "tenant_name"
      prompt: "Which tenant will the Endpoint Group be located in"
      private: no
    - name: "bd_name"
      prompt: "What is the name of the new Bridge Domain?"
      private: no
    - name: "ap_name"
      prompt: "Application Profile Name"
      private: no
    - name: "epg1_name"
      prompt: "Endpoint 1 Group Name"
      private: no
    - name: "epg2_name"
      prompt: "Endpoint 2 Group Name"
      private: no
    - name: "epg3_name"
      prompt: "Endpoint 3 Group Name"
      private: no
#    - name: "description"
#      prompt: "Application Profile Description"
#      private: no
  gather_facts: no
  connection: local
  roles:
    - aci_3tier_epg_add
