---
#- hosts: localhost
#  connection: local
#  roles:
#    - known_hosts

- hosts: apic
  vars_prompt:
    - name: "user"
      prompt: "Username"
      private: no
    - name: "password"
      prompt: "Password"
      private: yes
    - name: "vlan_number"
      prompt: "VLAN Number"
      private: no
    - name: "gateway"
      prompt: "Default Gateway"
      private: "no"
    - name: "mask"
      prompt: "Subnet Mask"
      private: no
    - name: "description"
      prompt: "VLAN  Description"
      private: no
  gather_facts: no
  connection: local
  roles:
    - aci_snap_add
    - jtc_bd_add
    - jtc_epg_add
    - jtc_contract_add
    - jtc_epg_domain_add
