---
#- hosts: localhost
#  connection: local
#  roles:
#    - known_hosts

- hosts: apic
  vars_prompt:
    - name: "user"
      prompt: "Username"
      private: no
    - name: "password"
      prompt: "Password"
      private: yes

    - name: "vlan_number"
      prompt: "VLAN Number"
      private: no

  gather_facts: no
  connection: local
  roles:
    - jtc_bd_remove
    - jtc_epg_remove
    # - jtc_contract_remove
    # - jtc_epg_domain_remove
