- name: Add a new Bridge Domain
  aci_bd:
    hostname: 10.207.10.100
    username: "{{ user }}"
    password: "{{ password }}"
    tenant: "{{ tenant_name }}"
    bd: "{{ bd_name }}"
    vrf: "{{ vrf_name }}"
    validate_certs: no
    state: present

- name: Add Subnet to Bridge Domain
  aci_bd_subnet:
    hostname: 10.207.10.100
    username: "{{ user }}"
    password: "{{ password }}"
    tenant: "{{ tenant_name }}"
    bd: "{{ bd_name }}"
    gateway: "{{ gateway }}"
    mask: "{{ mask }}"
    validate_certs: no
    scope: public
