- name: Add a new Physical domain to EPG Binding
  aci_epg_to_domain:
    host: 10.207.10.100
    username: "{{ user }}"
    password: "{{ password }}"
    tenant: JTC
    ap: jtc_vlans
    epg: "VLAN_{{ vlan_number }}"
    domain: DTLK_Phys
    domain_type: phys
    validate_certs: no
    state: present
