- name: Create a new Filter
  aci_filter_entry:
    hostname: 10.207.10.100
    username: "{{ user }}"
    password: "{{ password }}"
    tenant: "{{ tenant_name }}"
    filter: "{{ filter_name }}"
    entry: "any"
    ether_type: "ip"
    ip_protocol: "tcp"
    state: present
    validate_certs: no 
#  delegate_to: localhost