- name: Add a new EPG 1
  aci_epg:
    hostname: 10.207.10.100
    username: "{{ user }}"
    password: "{{ password }}"
    tenant: JTC
    ap: jtc_vlans
    epg: "VLAN_{{ vlan_number }}"
    bd: "VLAN_{{ vlan_number }}"
    state: present
    validate_certs: no 
#  delegate_to: localhost
