- name: Remove LLDP Enable Policy
  aci_interface_policy_lldp:
    hostname: 10.207.10.100
    username: "{{ user }}"
    password: "{{ password }}"
    lldp_policy: ANS_LLDP_TR_Enable
    description: "LLDP Send and Receive Enable"
    validate_certs: no
    state: absent

- name: Remove LLDP Disable Policy
  aci_interface_policy_lldp:
    hostname: 10.207.10.100
    username: "{{ user }}"
    password: "{{ password }}"
    lldp_policy: ANS_LLDP_TR_Disable
    description: "LLDP Send and Receive Enable"
    validate_certs: no
    state: absent

- name: Remove LLDP Transmit Disable Receive Enable Policy
  aci_interface_policy_lldp:
    hostname: 10.207.10.100
    username: "{{ user }}"
    password: "{{ password }}"
    lldp_policy: ANS_LLDP_T_Disable_R_Enable
    description: "LLDP Transmit Disable and Receive Enable"
    validate_certs: no
    state: absent

- name: Remove LLDP Transmit Enable Receive Disable Policy
  aci_interface_policy_lldp:
    hostname: 10.207.10.100
    username: "{{ user }}"
    password: "{{ password }}"
    lldp_policy: ANS_LLDP_T_Enable_R_Disable
    description: "LLDP Transmit Enable and Receive Disable"
    validate_certs: no
    state: absent