- name: Create a new Filter
  aci_filter:
    hostname: 10.207.10.100
    username: "{{ user }}"
    password: "{{ password }}"
    tenant: "{{ tenant_name }}"
    filter: "{{ filter_name }}"
    state: present
    validate_certs: no 
#  delegate_to: localhost