- name: Adding new VPN User
  win_domain_user:
    name: "{{ new_user }}"
    password: "{{ new_user_password }}"
    state: present
    domain_username: "{{ admin_user }}"
    domain_password: "{{ admin_password }}"
    domain_server: "e0msft0ad01.datalinklabs.local"
    groups:
      - Users