- name: Create a new Contract
  aci_contract:
    hostname: 10.207.10.100
    username: "{{ user }}"
    password: "{{ password }}"
    tenant: "{{ tenant_name }}"
    contract: "{{ contract_name }}"
    scope: application-profile
    state: present
    validate_certs: no 
#  delegate_to: localhost