- name: Add LACP Policy
  aci_interface_policy_port_channel:
    hostname: 10.207.10.100
    username: "{{ user }}"
    password: "{{ password }}"
    port_channel: ANS_LACP_Enable
    description: "LACP Enabled by Ansible"
    mode: active
    validate_certs: no
    state: present