- name: Add a new AP
  aci_ap:
    hostname: 10.207.10.100
    username: "{{ user }}"
    password: "{{ password }}"
    tenant: "{{ tenant_name }}"
    ap: "{{ ap_name }}"
    description: "{{ ap_description }}"
    state: present
    validate_certs: no 
#  delegate_to: localhost
