- name: For each host, scan for its ssh public key
  shell: "ssh-keyscan -H {{ item }}"
  with_items: "{{ ssh_known_hosts }}"
  register: ssh_known_host_results
  ignore_errors: yes

- name: Remove the public key in the '{{ ssh_known_hosts_file }}'
  known_hosts:
    name: "{{ item.item }}"
    state: "absent"
    path: "{{ ssh_known_hosts_file }}"
  with_items: "{{ ssh_known_host_results.results }}"

- name: update known_hosts file on ansible system
  shell: |
        for host in `grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" /etc/ansible/hosts`
          do
             ssh-keyscan -H $host >> "{{ ssh_known_hosts_file }}"
          done
