- name: Remove CDP Enable Policy
  aci_rest:
    hostname: 10.207.10.100
    username: "{{ user }}"
    password: "{{ password }}"
    validate_certs: no
    method: post
    path: /api/mo/uni/infra.json
    content:
       cdpIfPol:
         attributes:
           name: ANS_CDP_Enable
           status: deleted

- name: Remove CDP Disable Policy
  aci_rest:
    hostname: 10.207.10.100
    username: "{{ user }}"
    password: "{{ password }}"
    validate_certs: no
    method: post
    path: /api/mo/uni/infra.json
    content:
       cdpIfPol:
         attributes:
           name: ANS_CDP_Disable
           status: deleted