#
# Filename:             2_ansible_pure_playbook.yml
# By:                   Dan Burkland
# Date:                 2019-02-10
# Purpose:              Playbook that creates a new volume and a snapshot of that volume on a Pure Array
# Version:              1.0
# Usage Instructions:   ansible-playbook new_purestorage_volume.yml
---
- hosts: localhost
  name: Create or delete Pure Storage volumes
  connection: local
  gather_facts: false
  vars:
    ##################################
    #   General Pure Array Section   #
    ##################################
    fa_url: "e7pure0fa01.datalinklabs.local"
    fa_apitoken: "492beb59-aa30-a8a5-6ba6-af370cb63932"
    cleanup: false
    ##################################
    #      Pure Volume  Section      #
    ##################################
    clone_prefix: "clone_"
    volumes:
      testvol1:
        size: "10G"
        snap_name: "testsnap1"
      testvol2:
        size: "10G"
        snap_name: "testsnap2"

  tasks:
    - name: Delete a snapshot of each specified volume
      purefa_snap:
        api_token: "{{ fa_apitoken }}"
        fa_url: "{{ fa_url }}"
        state: absent
        name: "{{ name }}"
        suffix: "{{ suffix }}"
        eradicate: true
      with_dict: "{{ volumes }}"
      loop_control:
        loop_var: outer_item
      vars:
        name: "{{ outer_item.key }}"
        suffix: "{{ outer_item.value.snap_name }}"
      when:
        - cleanup

    - name: Delete each specified volume
      purefa_volume:
        api_token: "{{ fa_apitoken }}"
        fa_url: "{{ fa_url }}"
        state: absent
        name: "{{ name }}"
        size: "{{ size }}"
        eradicate: true
      with_dict: "{{ volumes }}"
      loop_control:
        loop_var: outer_item
      vars:
        name: "{{ outer_item.key }}"
        size: "{{ outer_item.value.size }}"
      when:
        - cleanup
    
    - name: Create each specified volume
      purefa_volume:
        api_token: "{{ fa_apitoken }}"
        fa_url: "{{ fa_url }}"
        state: present
        name: "{{ name }}"
        size: "{{ size }}"
      with_dict: "{{ volumes }}"
      loop_control:
        loop_var: outer_item
      vars:
        name: "{{ outer_item.key }}"
        size: "{{ outer_item.value.size }}"
      when:
        - not cleanup

    - name: Create a snapshot of each specified volume
      purefa_snap:
        api_token: "{{ fa_apitoken }}"
        fa_url: "{{ fa_url }}"
        state: present
        name: "{{ name }}"
        suffix: "{{ suffix }}"
      with_dict: "{{ volumes }}"
      loop_control:
        loop_var: outer_item
      vars:
        name: "{{ outer_item.key }}"
        suffix: "{{ outer_item.value.snap_name }}"
      when:
        - not cleanup
