---
#- hosts: localhost
#  connection: local
#  roles:
#    - known_hosts

- hosts: apic
  vars_prompt:
    - name: "user"
      prompt: "Username"
      private: no
    - name: "password"
      prompt: "Password"
      private: yes
    - name: "tenant_name"
      prompt: "Which tenant will the Bridge Domain located in"
      private: no
    - name: "bd_name"
      prompt: "What is the name of the new Bridge Domain?"
      private: no
    - name: "gateway"
      prompt: "Gateway"
      private: no
    - name: "mask"
      prompt: "Subnet Mask"
      private: no
    - name: "vrf_name"
      prompt: "what is the name of the VRF in which the Bridge Domain will be associated?"
      private: no
  gather_facts: no
  connection: local
  roles:
    - aci_bd_add
