- name: installing k8s on the master node
  shell: 'kubeadm init --pod-network-cidr="{{ cni_network }}" | tail -2 > /tmp/workerinstall.txt'
  register: output
- debug: msg="{{ output.stdout }}"
- debug: msg="{{ output.stderr }}"

- name: setting up directory structure for kubectl
  file:
    path: /home/sysadmin/.kube
    state: directory
    mode: 0755
    owner: sysadmin
    group: sysadmin

- name: copy config files to .kube directory
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/sysadmin/.kube/config
    owner: sysadmin
    group: sysadmin
    remote_src: yes

